
package view;

import connectionDB.koneksi;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class formlaporan extends javax.swing.JFrame {

    /**
     * Creates new form formlaporan
     */
    public formlaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        blpetugas = new javax.swing.JButton();
        blpenjualan = new javax.swing.JButton();
        blpemasok = new javax.swing.JButton();
        blstokobat = new javax.swing.JButton();
        blpembelian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelutama.setBackground(new java.awt.Color(0, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATA LAPORAN TOKO OBAT ANGGA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        blpetugas.setBackground(new java.awt.Color(255, 51, 51));
        blpetugas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        blpetugas.setText("LAPORAN PETUGAS");
        blpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blpetugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blpetugasMouseExited(evt);
            }
        });
        blpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blpetugasActionPerformed(evt);
            }
        });

        blpenjualan.setBackground(new java.awt.Color(255, 51, 51));
        blpenjualan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        blpenjualan.setText("LAPORAN PENJUALAN");
        blpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blpenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blpenjualanMouseExited(evt);
            }
        });
        blpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blpenjualanActionPerformed(evt);
            }
        });

        blpemasok.setBackground(new java.awt.Color(255, 51, 51));
        blpemasok.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        blpemasok.setText("LAPORAN PEMASOK");
        blpemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blpemasokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blpemasokMouseExited(evt);
            }
        });
        blpemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blpemasokActionPerformed(evt);
            }
        });

        blstokobat.setBackground(new java.awt.Color(255, 51, 51));
        blstokobat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        blstokobat.setText("LAPORAN STOK OBAT");
        blstokobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blstokobatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blstokobatMouseExited(evt);
            }
        });
        blstokobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blstokobatActionPerformed(evt);
            }
        });

        blpembelian.setBackground(new java.awt.Color(255, 51, 51));
        blpembelian.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        blpembelian.setText("LAPORAN PEMBELIAN");
        blpembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blpembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blpembelianMouseExited(evt);
            }
        });
        blpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blpembelianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blpembelian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blpenjualan)
                    .addComponent(blpemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blstokobat, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373))
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blpemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(blstokobat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void blpetugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpetugasMouseEntered
        blpetugas.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_blpetugasMouseEntered

    private void blpetugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpetugasMouseExited
        blpetugas.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_blpetugasMouseExited

    private void blpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blpetugasActionPerformed
        try {
            String namaFile = "src/Laporan/petugas.jasper";
            Connection conn = new koneksi().connect();
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false); //coba
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_blpetugasActionPerformed

    private void blpenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpenjualanMouseEntered
        // TODO add your handling code here:
        blpenjualan.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_blpenjualanMouseEntered

    private void blpenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpenjualanMouseExited
        // TODO add your handling code here:
        blpenjualan.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_blpenjualanMouseExited

    private void blpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blpenjualanActionPerformed
        // TODO add your handling code here:
        laporanpenjualan lp = new laporanpenjualan();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_blpenjualanActionPerformed

    private void blpemasokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpemasokMouseEntered
        // TODO add your handling code here:
        blpemasok.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_blpemasokMouseEntered

    private void blpemasokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpemasokMouseExited
        // TODO add your handling code here:
        blpemasok.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_blpemasokMouseExited

    private void blpemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blpemasokActionPerformed
        try {
            String namaFile = "src/Laporan/pemasok.jasper";
            Connection conn = new koneksi().connect();
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false); //coba
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_blpemasokActionPerformed

    private void blstokobatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blstokobatMouseEntered
        // TODO add your handling code here:
        blstokobat.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_blstokobatMouseEntered

    private void blstokobatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blstokobatMouseExited
        // TODO add your handling code here:
        blstokobat.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_blstokobatMouseExited

    private void blstokobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blstokobatActionPerformed
        try {
            String namaFile = "src/Laporan/stokobat.jasper";
            Connection conn = new koneksi().connect();
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false); //coba
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_blstokobatActionPerformed

    private void blpembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpembelianMouseEntered
        // TODO add your handling code here:
        blpembelian.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_blpembelianMouseEntered

    private void blpembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blpembelianMouseExited
        // TODO add your handling code here:
        blpembelian.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_blpembelianMouseExited

    private void blpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blpembelianActionPerformed
        // TODO add your handling code here:
        laporanpembelian laporan = new laporanpembelian();
        laporan.setVisible(true);
        dispose();
    }//GEN-LAST:event_blpembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formlaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blpemasok;
    private javax.swing.JButton blpembelian;
    private javax.swing.JButton blpenjualan;
    private javax.swing.JButton blpetugas;
    private javax.swing.JButton blstokobat;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelutama;
    // End of variables declaration//GEN-END:variables
}
