/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author User
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        bpetugas = new javax.swing.JButton();
        blaporan = new javax.swing.JButton();
        bstok = new javax.swing.JButton();
        bpemasok = new javax.swing.JButton();
        bpembelian = new javax.swing.JButton();
        bpenjualan = new javax.swing.JButton();
        panelheader = new javax.swing.JPanel();
        labeljudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klinik Angga Bersahabat");

        panelutama.setBackground(new java.awt.Color(0, 255, 51));

        bpetugas.setBackground(new java.awt.Color(255, 51, 51));
        bpetugas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bpetugas.setText("PETUGAS");
        bpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpetugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpetugasMouseExited(evt);
            }
        });
        bpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpetugasActionPerformed(evt);
            }
        });

        blaporan.setBackground(new java.awt.Color(255, 51, 51));
        blaporan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        blaporan.setText("LAPORAN");
        blaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blaporanMouseExited(evt);
            }
        });
        blaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaporanActionPerformed(evt);
            }
        });

        bstok.setBackground(new java.awt.Color(255, 51, 51));
        bstok.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bstok.setText("STOK OBAT");
        bstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bstokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bstokMouseExited(evt);
            }
        });
        bstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstokActionPerformed(evt);
            }
        });

        bpemasok.setBackground(new java.awt.Color(255, 51, 51));
        bpemasok.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bpemasok.setText("PEMASOK");
        bpemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpemasokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpemasokMouseExited(evt);
            }
        });
        bpemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpemasokActionPerformed(evt);
            }
        });

        bpembelian.setBackground(new java.awt.Color(255, 51, 51));
        bpembelian.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bpembelian.setText("PEMBELIAN");
        bpembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpembelianMouseExited(evt);
            }
        });
        bpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpembelianActionPerformed(evt);
            }
        });

        bpenjualan.setBackground(new java.awt.Color(255, 51, 51));
        bpenjualan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bpenjualan.setText("PENJUALAN");
        bpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpenjualanMouseExited(evt);
            }
        });
        bpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpenjualanActionPerformed(evt);
            }
        });

        panelheader.setBackground(new java.awt.Color(0, 204, 204));

        labeljudul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labeljudul.setForeground(new java.awt.Color(102, 0, 0));
        labeljudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeljudul.setText("KLINIK KECANTIKAN DUTA");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/newlogoangga - Copy.png"))); // NOI18N

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labeljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labeljudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(bpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(bstok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bpemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(bpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(bpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(blaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addComponent(panelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bstok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(blaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bpetugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpetugasMouseEntered
        // TODO add your handling code here:
        bpetugas.setBackground(new Color(255,0,0));
        bpetugas.setForeground(Color.white);
    }//GEN-LAST:event_bpetugasMouseEntered

    private void bpetugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpetugasMouseExited
        // TODO add your handling code here:
        bpetugas.setBackground(new Color(255,51,51));
        bpetugas.setForeground(Color.black);
    }//GEN-LAST:event_bpetugasMouseExited

    private void bstokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bstokMouseEntered
        // TODO add your handling code here:
        bstok.setBackground(new Color(255,0,0));
        bstok.setForeground(Color.white);
    }//GEN-LAST:event_bstokMouseEntered

    private void bstokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bstokMouseExited
        // TODO add your handling code here:
        bstok.setBackground(new Color(255,51,51));
        bstok.setForeground(Color.black);
    }//GEN-LAST:event_bstokMouseExited

    private void bpemasokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpemasokMouseEntered
        // TODO add your handling code here:
        bpemasok.setBackground(new Color(255,0,0));
        bpemasok.setForeground(Color.white);
    }//GEN-LAST:event_bpemasokMouseEntered

    private void bpemasokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpemasokMouseExited
        bpemasok.setBackground(new Color(255,51,51));
        bpemasok.setForeground(Color.black);
    }//GEN-LAST:event_bpemasokMouseExited

    private void bpembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpembelianMouseEntered
        bpembelian.setBackground(new Color(255,0,0));
        bpembelian.setForeground(Color.white);
    }//GEN-LAST:event_bpembelianMouseEntered

    private void bpembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpembelianMouseExited
        bpembelian.setBackground(new Color(255,51,51));
        bpembelian.setForeground(Color.black);
    }//GEN-LAST:event_bpembelianMouseExited

    private void bpenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpenjualanMouseEntered
        bpenjualan.setBackground(new Color(255,0,0));
        bpenjualan.setForeground(Color.white);
    }//GEN-LAST:event_bpenjualanMouseEntered

    private void bpenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpenjualanMouseExited
        bpenjualan.setBackground(new Color(255,51,51));
        bpenjualan.setForeground(Color.black);
    }//GEN-LAST:event_bpenjualanMouseExited

    private void blaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blaporanMouseEntered
        blaporan.setBackground(new Color(255,0,0));
        blaporan.setForeground(Color.white);
    }//GEN-LAST:event_blaporanMouseEntered

    private void blaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blaporanMouseExited
        blaporan.setBackground(new Color(255,51,51));
        blaporan.setForeground(Color.black);
    }//GEN-LAST:event_blaporanMouseExited

    private void bpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpetugasActionPerformed
        formpetugas petugas = new formpetugas();
        petugas.setVisible(true);
    }//GEN-LAST:event_bpetugasActionPerformed

    private void bstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstokActionPerformed
        formstokobat stokobat = new formstokobat();
        stokobat.setVisible(true);
    }//GEN-LAST:event_bstokActionPerformed

    private void bpemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpemasokActionPerformed
        formpemasok pemasok = new formpemasok();
        pemasok.setVisible(true);
    }//GEN-LAST:event_bpemasokActionPerformed

    private void bpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpembelianActionPerformed
        transaksipembelian pembelian = new transaksipembelian();
        pembelian.setVisible(true);
    }//GEN-LAST:event_bpembelianActionPerformed

    private void bpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpenjualanActionPerformed
        transaksipenjualan penjualan = new transaksipenjualan();
        penjualan.setVisible(true);
    }//GEN-LAST:event_bpenjualanActionPerformed

    private void blaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaporanActionPerformed
        formlaporan laporan = new formlaporan();
        laporan.setVisible(true);
    }//GEN-LAST:event_blaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blaporan;
    private javax.swing.JButton bpemasok;
    private javax.swing.JButton bpembelian;
    private javax.swing.JButton bpenjualan;
    private javax.swing.JButton bpetugas;
    private javax.swing.JButton bstok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JPanel panelheader;
    private javax.swing.JPanel panelutama;
    // End of variables declaration//GEN-END:variables
}
